#!/usr/bin/env python3
""" Writing strings to REDIS """
import redis
import uuid
from typing import Union


class Cache:
    """ Initializing the class """


    def __init__(self):
        """ creating an instance of the redis client """
        self._redis = redis.Redis()
        self._redis.flushdb()
    def store(self, data: Union[str, bytes, int, float]) -> str:
        """ Storing the data in the db and returning the id """
        key = str(uuid.uuid4())
        self._redis.set(key, data)
        return key
    def get(self, key: str, fn: Callable = None) -> Union[str, bytes, int, None]:
        data = self._redis.get(key)
        if data is None:
            return None
        if fn is not None:
            return fn(data)
        return data

    def get_str(self, key: str) -> Union[str, None]:
        return self.get(key, fn=lambda d: d.decode('utf-8') if isinstance(d, bytes) else d)

    def get_int(self, key: str) -> Union[int, None]:
        return self.get(key, fn=lambda d: int(d) if d.isdigit() else None)
    def count_calls(method: Callable) -> Callable:
        @wraps(method)
        def wrapper(self, *args, **kwargs):
            key = method.__qualname__
            self._redis.incr(key)
            return method(self, *args, **kwargs)
        return wrapper

    @count_calls
    def store(self, data: Union[str, bytes, int, float]) -> str:
        key = str(uuid.uuid4())
        self._redis.set(key, data)
        return key
